name: Scrape + Export annonces

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Crée data/links.txt (1 URL par ligne)
      - name: Create links.txt
        shell: bash
        run: |
          mkdir -p data
          : > data/links.txt
          echo "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200&camera=10_1.1490573_43.7260169_0_0" >> data/links.txt
          echo "https://www.logic-immo.com/classified-search?distributionTypes=Rent&estateTypes=House&locations=POCOFR1841,POCOFR1795,POCOFR1845&numberOfRoomsMin=4&priceMax=1200" >> data/links.txt
          echo "https://www.entreparticuliers.com/annonces-immobilieres/location/maison/bouloc-31620?piecesNbMin=4&prixMax=1200" >> data/links.txt
          echo "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200" >> data/links.txt

      # Crée data/communes.json via Python (évite les quotes foireuses)
      - name: Create communes.json
        shell: bash
        run: |
          python3 - <<'PY'
          import json, os
          os.makedirs("data", exist_ok=True)
          d = {
            "31620": ["Fronton","Bouloc","Castelnau-d'Estrétefonds","Cépet","Saint-Rustice","Villeneuve-lès-Bouloc","Villaudric","Vacquiers"],
            "31150": ["Fenouillet","Gagnac-sur-Garonne","Gratentour","Lespinasse","Bruguières"],
            "31790": ["Saint-Jory","Saint-Sauveur"]
          }
          with open("data/communes.json","w",encoding="utf-8") as f:
            json.dump(d, f, ensure_ascii=False, indent=2)
          PY

      - name: Install deps
        run: npm ci || npm i

      - name: Install Playwright package
        run: npm install playwright@^1.47.0

      - name: Download Chromium for Playwright
        run: npx playwright install chromium

      - name: Run build (scrape + export)
        run: npm run build

      # ✅ Commit + rebase-safe, on ajoute TOUT pour éviter "unstaged changes"
      - name: Commit results (rebase-safe with retry)
        env:
          BRANCH: ${{ github.ref_name }}
        shell: bash
        run: |
         set -euo pipefail
         git config user.name  "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
    # 1) Stage tout (évite "unstaged changes")
    git add -A
    git commit -m "Update annonces (bot)" || echo "No changes"

    # 2) Rebase sur la branche distante + 3 tentatives de push en cas de course
    for i in 1 2 3; do
      echo "Attempt $i: rebase + push…"
      # autoStash évite d'écraser des modifs locales non committées pendant le rebase
      git -c rebase.autoStash=true pull --rebase origin "$BRANCH" || git rebase --abort
      if git push origin HEAD:"$BRANCH"; then
        echo "Push OK"
        exit 0
      fi
      echo "Conflit ou course, on retente…"
      sleep $((2*i))
    done

    echo "Échec après 3 tentatives. Dernier recours: force-with-lease (désactivé par défaut)."
    exit 1

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: annonces-csv
          path: data/annonces.csv
