name: Scrape + Export annonces (links + EP par ville)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure links.txt (tes liens)
        shell: bash
        run: |
          mkdir -p data
          printf "%s\n"             "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200&camera=10_1.1490573_43.7260169_0_0"             "https://www.logic-immo.com/classified-search?distributionTypes=Rent&estateTypes=House&locations=POCOFR1841,POCOFR1795,POCOFR1845&numberOfRoomsMin=4&priceMax=1200"             "https://www.entreparticuliers.com/annonces-immobilieres/location/maison/bouloc-31620?piecesNbMin=4&prixMax=1200"             "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200"             > data/links.txt

      - name: Ensure communes.json (via Node)
        shell: bash
        run: |
          node -e "const fs=require('fs');fs.mkdirSync('data',{recursive:true});const p='data/communes.json';if(!fs.existsSync(p)){const d={'31620':['Fronton','Bouloc','Castelnau-d\'Estrétefonds','Cépet','Saint-Rustice','Villeneuve-lès-Bouloc','Villaudric','Vacquiers'],'31150':['Fenouillet','Gagnac-sur-Garonne','Gratentour','Lespinasse','Bruguières'],'31790':['Saint-Jory','Saint-Sauveur']};fs.writeFileSync(p,JSON.stringify(d,null,2),'utf8');}"

      - run: npm ci || npm i
      - run: npx playwright install --with-deps chromium
      - run: npm run build

      - name: Commit data (rebase-safe)
  shell: bash
  run: |
    BRANCH=${GITHUB_REF_NAME:-main}
    git config user.name  "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    git add data/annonces.json data/annonces.csv data/annonces_flat.html || true
    git commit -m "Update annonces (bot)" || echo "No changes to commit"

    git pull --rebase origin "$BRANCH" || git rebase --abort
    git push origin HEAD:"$BRANCH"


      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: annonces-csv
          path: data/annonces.csv
