name: Scrape + Export annonces (links + EP par ville)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"   # toutes les 2h

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Checkout avec historique complet (rebase possible)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Assurer data/links.txt (tes liens)
      - name: Ensure links.txt (tes liens)
  shell: bash
  run: |
    mkdir -p data
    cat > data/links.txt <<'LINKS'
https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200&camera=10_1.1490573_43.7260169_0_0
https://www.logic-immo.com/classified-search?distributionTypes=Rent&estateTypes=House&locations=POCOFR1841,POCOFR1795,POCOFR1845&numberOfRoomsMin=4&priceMax=1200
https://www.entreparticuliers.com/annonces-immobilieres/location/maison/bouloc-31620?piecesNbMin=4&prixMax=1200
https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200
LINKS


      # (Optionnel) Assurer data/communes.json s’il manque
      - name: Ensure communes.json (par défaut)
        run: |
          if [ ! -f data/communes.json ]; then
            mkdir -p data
            cat > data/communes.json <<'JSON'
{
  "31620": ["Fronton","Bouloc","Castelnau-d'Estrétefonds","Cépet","Saint-Rustice","Villeneuve-lès-Bouloc","Villaudric","Vacquiers"],
  "31150": ["Fenouillet","Gagnac-sur-Garonne","Gratentour","Lespinasse","Bruguières"],
  "31790": ["Saint-Jory","Saint-Sauveur"]
}
JSON
          fi

      # 4) Dépendances & Playwright
      - run: npm ci || npm i
      - run: npx playwright install --with-deps chromium

      # 5) Scrape + export (JSON, CSV, HTML)
      - run: npm run build

      # 6) Commit + rebase-safe push
      - name: Commit data (rebase-safe)
        run: |
          BRANCH="${GITHUB_REF_NAME:-main}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/annonces.json data/annonces.csv data/annonces_flat.html || true
          git commit -m "Update annonces (bot)" || echo "No changes to commit"

          git pull --rebase origin "$BRANCH" || git rebase --abort
          git push origin HEAD:"$BRANCH"

      # 7) Artifact CSV (facile à télécharger depuis l’onglet Actions)
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: annonces-csv
          path: data/annonces.csv
