name: Scrape + Export annonces (links + EP par ville)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"   # toutes les 2h

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Crée data/links.txt
      - name: Ensure links.txt
        shell: bash
        run: |
          mkdir -p data
          printf "%s\n" \
            "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200&camera=10_1.1490573_43.7260169_0_0" \
            "https://www.logic-immo.com/classified-search?distributionTypes=Rent&estateTypes=House&locations=POCOFR1841,POCOFR1795,POCOFR1845&numberOfRoomsMin=4&priceMax=1200" \
            "https://www.entreparticuliers.com/annonces-immobilieres/location/maison/bouloc-31620?piecesNbMin=4&prixMax=1200" \
            "https://www.bienici.com/recherche/location/31620,31150,31790/maisonvilla/4-pieces-et-plus?prix-max=1200" \
            > data/links.txt

      # Crée data/communes.json (JSON compact, sans caractères spéciaux piégeux)
      - name: Ensure communes.json
        shell: bash
        run: |
          mkdir -p data
          if [ ! -f data/communes.json ]; then
            printf '%s\n' '{"31620":["Fronton","Bouloc","Castelnau-dEstrétefonds","Cépet","Saint-Rustice","Villeneuve-lès-Bouloc","Villaudric","Vacquiers"],"31150":["Fenouillet","Gagnac-sur-Garonne","Gratentour","Lespinasse","Bruguières"],"31790":["Saint-Jory","Saint-Sauveur"]}' > data/communes.json
          fi

      - run: npm ci || npm i
      - run: npx playwright install --with-deps chromium
      - run: npm run build

      - name: Commit data (rebase-safe)
        shell: bash
        run: |
          BRANCH="${GITHUB_REF_NAME:-main}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/annonces.json data/annonces.csv data/annonces_flat.html || true
          git commit -m "Update annonces (bot)" || echo "No changes to commit"

          git pull --rebase origin "$BRANCH" || git rebase --abort
          git push origin HEAD:"$BRANCH"

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: annonces-csv
          path: data/annonces.csv